services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    environment:
      NODE_ENV: "production"
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_EXTERNAL: ${DATABASE_URL_EXTERNAL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      NEXT_PUBLIC_CLIENTVAR: ${NEXT_PUBLIC_CLIENTVAR}
    depends_on:
      - db
    exclude_from_hc: true

  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration:
    build:
      context: .
      dockerfile: ./docker/drizzle.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_EXTERNAL: ${DATABASE_URL_EXTERNAL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      SKIP_ENV_VALIDATION: "1"
    command: ["pnpm", "run", "db:migrate"]
    depends_on:
      db:
        condition: service_healthy
    exclude_from_hc: true

  db-seed:
    build:
      context: .
      dockerfile: ./docker/drizzle.Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_EXTERNAL: ${DATABASE_URL_EXTERNAL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      SKIP_ENV_VALIDATION: "1"
    command: ["pnpm", "run", "db:seed"]
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
    exclude_from_hc: true

  keycloak:
    build:
      context: .
      dockerfile: ./docker/keycloak.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command:
      - "start-dev"
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_PASSWORD: "${POSTGRES_PASSWORD}"
      KC_DB_USERNAME: "${POSTGRES_USER}"
      KC_DB_SCHEMA: "keycloak"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true" # Abilita HTTP
      #KC_HTTP_PORT: "8081"
      #KC_HTTP_RELATIVE_PATH: "/auth"
      #KC_HTTP_MANAGEMENT_RELATIVE_PATH: "/auth"
      #KC_PROXY_PROTOCOL_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      TZ: ${TIMEZONE:-UTC}
    healthcheck:
      test:
        - CMD-SHELL
        - "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
      interval: 10s
      timeout: 5s
      retries: 5
    exclude_from_hc: true

  # cron:
  #   image: alpine/curl
  #   command: >
  #     sh -c "
  #       echo '*/10 * * * * curl -X POST http://app:3000/api/db/clear' > /etc/crontabs/root && \
  #       crond -f -l 2
  #     "
  #   depends_on:
  #     - app
