name: Deploy Production on Vercel

inputs:
  VERCEL_TOKEN:
    description: vercel token
    required: true

runs:
  using: composite
  steps:
    - name: 📤 Pull Vercel Environment Information
      run: pnpm dlx vercel env pull .env --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: 📤 Pull Vercel Environment Information
      run: pnpm dlx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: 🏗 Build Project Artifacts
      run: pnpm dlx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      shell: bash

    - name: 🚀 Deploy Project Artifacts to Vercel
      run: pnpm dlx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      shell: bash
