name: Deploy Preview

on: [pull_request]

env:
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }} # change this to your database username
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }} # You can generate a an API key in your account settings
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  SKIP_ENV_VALIDATION: 1

runs:
  using: composite
  steps:
    - name: Run Migrations
      run: |
        touch .env

        echo DATABASE_URL=${{ steps.create-branch.outputs.db_url_with_pooler }} >> .env
        echo DATABASE_URL_UNPOOLED=${{ steps.create-branch.outputs.db_url }} >> .env

        pnpm run db:generate
        pnpm run db:migrate

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ env.VERCEL_TOKEN }}

    - name: Deploy Preview to Vercel
      id: deploy
      run: echo preview_url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

    - name: Comment on Pull Request
      uses: thollander/actions-comment-pull-request@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
          Neon branch :elephant: : https://console.neon.tech/app/projects/${{ vars.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}
