name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - main

runs:
  using: composite
  runs-on: ubuntu-latest
  steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0ABCEB503 }}
        action: "close"
        app_location: "/" # App source code path
