name: Deploy Preview on Vercel

inputs:
  DATABASE_URL:
    description: database url with pooler
    required: true
  DATABASE_URL_UNPOOLED:
    description: database url
    required: true
  VERCEL_TOKEN:
    description: vercel token
    required: true
outputs:
  preview_url:
    description: "Preview URL"
    value: ${{ steps.deploy.outputs.preview_url }}

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ inputs.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ inputs.VERCEL_TOKEN }}

    - name: Deploy Preview to Vercel
      id: deploy
      run: echo preview_url=$(vercel deploy --prebuilt --token=${{ inputs.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT
