name: Deploy Preview on Vercel

inputs:
  DATABASE_URL:
    description: database url with pooler
    required: true
  DATABASE_URL_UNPOOLED:
    description: database url
    required: true

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Preview to Vercel
      id: deploy
      run: echo preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT

    - name: Comment on Pull Request
      uses: thollander/actions-comment-pull-request@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
          Neon branch :elephant: : https://console.neon.tech/app/projects/${{ vars.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}
