name: Deploy Preview on Vercel

inputs:
  VERCEL_TOKEN:
    description: vercel token
    required: true
outputs:
  preview_url:
    description: "Preview URL"
    value: ${{ steps.deploy.outputs.preview_url }}

runs:
  using: composite
  steps:
    - name: 📤 Pull Vercel Environment Information
      run: pnpm dlx vercel env pull .env --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    - name: 📤 Pull Vercel Environment Information
      run: pnpm dlx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: 🏗 Build Project Artifacts
      run: pnpm dlx vercel build --token=${{ inputs.VERCEL_TOKEN }}
      shell: bash

    - name: 🚀 Deploy Project Artifacts to Vercel
      id: deploy
      run: echo preview_url=$(pnpm dlx vercel deploy --prebuilt --token=${{ inputs.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT
      shell: bash
