name: Deploy Preview

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }} # You can generate a an API key in your account settings
  NEON_DATABASE_NAME: neondb # Change this to your db name
  NEON_DATABASE_USERNAME: neondb_owner # Change this to your db user
  SKIP_ENV_VALIDATION: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: CI checks
    uses: ./.github/workflows/ci.yml

  create_neon_branch:
    name: Create Neon Branch
    outputs:
      db_url: ${{ steps.create_branch.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create_branch.outputs.db_url_with_pooler }}
      branch_id: ${{ steps.create_branch.outputs.branch_id }}
    needs: ci
    if: github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies & tooling
        uses: ./.github/workflows/setup

      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Create Neon Branch
        id: create_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          # parent: main # optional (defaults to your primary branch)
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          database: ${{ env.NEON_DATABASE_NAME }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          api_key: ${{ env.NEON_API_KEY }}

      - name: Run Migrations
        run: pnpm run db:migrate
        env:
          DATABASE_URL: "${{ steps.create_branch.outputs.db_url_with_pooler }}" # to use pooled connection
          # DATABASE_URL: "${{ steps.create_branch.outputs.db_url }}" # OR to use unpooled connection

      - name: Post Schema Diff Comment to PR
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          compare_branch: preview/pr-${{ github.event.number }}-${{ steps.branch_name.outputs.current_branch }}
          database: ${{ env.NEON_DATABASE_NAME }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          api_key: ${{ env.NEON_API_KEY }}

  cleanup_preview:
    name: Cleanup preview
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/cleanup-preview.yml

  deploy_preview:
    name: Deploy preview
    if: github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened')
    needs: create_neon_branch
    uses: ./.github/workflows/deploy-preview.yml
    with:
      branch_id: ${{ needs.create_neon_branch.outputs.branch_id }}
    secrets:
      database_url: ${{ needs.create_neon_branch.outputs.db_url_with_pooler }}

  # deploy_staging:
  #   name: Deploy staging
  #   if: github.ref_name == 'develop'
  #   uses: ./.github/workflows/deploy-staging.yml

  deploy_production:
    name: Deploy production
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deploy-production.yml
